# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.convex_clusterpath <- function(X, W_idx, W_val, lambdas, eps_conv, eps_fusions, scale, save_clusterpath, burnin_iter, max_iter_conv) {
    .Call(`_CCMMR_convex_clusterpath`, X, W_idx, W_val, lambdas, eps_conv, eps_fusions, scale, save_clusterpath, burnin_iter, max_iter_conv)
}

.convex_clustering <- function(X, W_idx, W_val, eps_conv, eps_fusions, scale, save_clusterpath, burnin_iter, max_iter_conv, target_low, target_high, max_iter_phase_1, max_iter_phase_2, verbose, lambda_init, factor) {
    .Call(`_CCMMR_convex_clustering`, X, W_idx, W_val, eps_conv, eps_fusions, scale, save_clusterpath, burnin_iter, max_iter_conv, target_low, target_high, max_iter_phase_1, max_iter_phase_2, verbose, lambda_init, factor)
}

.fusion_threshold <- function(X, tau) {
    .Call(`_CCMMR_fusion_threshold`, X, tau)
}

.sparse_weights <- function(X, indices, distances, phi, k, connected, scale) {
    .Call(`_CCMMR_sparse_weights`, X, indices, distances, phi, k, connected, scale)
}

